// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDHWXFKlwUmROPYMCPJBlPbuhRl3W9R8k',
    appId: '1:774094771001:web:dde3e655316338e3cbcee8',
    messagingSenderId: '774094771001',
    projectId: 'inventaris-stock-baju',
    authDomain: 'inventaris-stock-baju.firebaseapp.com',
    storageBucket: 'inventaris-stock-baju.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeK7BLr9FEAmYti6Z80rnhqVvyOPUC34M',
    appId: '1:774094771001:android:608d90182c8646a4cbcee8',
    messagingSenderId: '774094771001',
    projectId: 'inventaris-stock-baju',
    storageBucket: 'inventaris-stock-baju.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF867Ov23cV87rTSd7Yl3jH7UQ2niwJ5U',
    appId: '1:774094771001:ios:a5f9d4c274bfdf69cbcee8',
    messagingSenderId: '774094771001',
    projectId: 'inventaris-stock-baju',
    storageBucket: 'inventaris-stock-baju.firebasestorage.app',
    iosBundleId: 'com.example.inventarisStockBaju',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF867Ov23cV87rTSd7Yl3jH7UQ2niwJ5U',
    appId: '1:774094771001:ios:a5f9d4c274bfdf69cbcee8',
    messagingSenderId: '774094771001',
    projectId: 'inventaris-stock-baju',
    storageBucket: 'inventaris-stock-baju.firebasestorage.app',
    iosBundleId: 'com.example.inventarisStockBaju',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDHWXFKlwUmROPYMCPJBlPbuhRl3W9R8k',
    appId: '1:774094771001:web:29348cc5e4c46a1acbcee8',
    messagingSenderId: '774094771001',
    projectId: 'inventaris-stock-baju',
    authDomain: 'inventaris-stock-baju.firebaseapp.com',
    storageBucket: 'inventaris-stock-baju.firebasestorage.app',
  );
}
